// Authentic Indian Market Laptop Catalog Data for GearGrid
// Verified against official manufacturer India portals and reputable authorized retailers.
// Real numeric INR prices, authentic hardware specifications, and product-specific image pairs.

export const LAPTOP_CATEGORIES_DATA = [
  {
    name: "Professional Laptops",
    description: "Enterprise mobile workstations, ultrabooks, and high-performance portable systems engineered for software engineers, digital creators, CAD architects, and business executives.",
    image: "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?auto=format&fit=crop&w=800&q=80",
  },
  {
    name: "Mac",
    description: "Apple MacBook Pro and MacBook Air laptops powered by M2, M3, and M4 Apple Silicon architectures featuring Liquid Retina XDR displays and industry-defining power efficiency.",
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80",
  },
  {
    name: "Gaming Laptops",
    description: "Enthusiast portable gaming machines featuring dedicated NVIDIA GeForce RTX graphics from RTX 3050 through flagship RTX 4090, high refresh rate displays, and vapor-chamber thermal engineering.",
    image: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&w=800&q=80",
  },
];

export const getLaptopProducts = (categoryMap) => {
  const proCatId = categoryMap["Professional Laptops"];
  const macCatId = categoryMap["Mac"];
  const gamingCatId = categoryMap["Gaming Laptops"];

  return [
    // =========================================================================
    // 10 PROFESSIONAL LAPTOPS (5 Apple Mac + 5 Windows Professional)
    // =========================================================================

    // 1. Apple MacBook Air 13" (M2)
    {
      title: "Apple MacBook Air 13.6-inch (M2 chip, 16GB Unified Memory, 256GB SSD) - Midnight",
      description: "Supercharged by the next-generation M2 chip, the redesigned MacBook Air combines incredible speed, all-day battery life, and a brilliant 13.6-inch Liquid Retina display in an ultrathin aluminum enclosure.",
      price: 99900,
      discountPrice: 94900,
      category: macCatId,
      brand: "Apple",
      stock: 35,
      featured: true,
      productType: "laptop",
      images: [
        { url: "/images/laptops/macbook_air_m2_midnight_1.jpg", publicId: "macbook_air_m2_midnight_1" },
        { url: "/images/laptops/macbook_air_m2_midnight_2.jpg", publicId: "macbook_air_m2_midnight_2" }
      ],
      rating: 4.8,
      numReviews: 184,
      specifications: {
        brand: "Apple",
        model: "MacBook Air 13 (M2)",
        processor: "Apple M2 (8-core CPU with 4 performance cores and 4 efficiency cores)",
        processorFamily: "Apple Silicon",
        cpuArchitecture: "ARM64 (5nm Enhanced)",
        powerClass: "Fanless Ultra-Efficient (15W)",
        gpu: "Apple M2 Integrated 8-core GPU",
        gpuModel: "Apple M2 8-core",
        gpuVram: 16,
        gpuClass: "Integrated Pro",
        tgp: 15,
        ram: "16GB Unified Memory",
        ramType: "Unified LPDDR5",
        ramUpgradeability: "Unified On-Package",
        storage: "256GB SSD",
        storageType: "Apple High-Speed NVMe SSD",
        storageInterface: "PCIe Gen4 on-board",
        displaySize: 13.6,
        resolution: "2560 x 1664 Liquid Retina",
        refreshRate: 60,
        panelType: "IPS Liquid Retina Display",
        colorCoverage: "100% DCI-P3 (500 nits brightness, True Tone technology)",
        battery: "52.6Whr Li-Polymer (up to 18 hours Apple TV app movie playback)",
        operatingSystem: "macOS Sequoia",
        weight: "1.24 kg",
        ports: ["MagSafe 3 charging port", "2x Thunderbolt / USB 4 ports", "3.5mm headphone jack with advanced high-impedance support"],
        wifi: "Wi-Fi 6 (802.11ax)",
        bluetooth: "Bluetooth 5.3",
        webcam: "1080p FaceTime HD camera with advanced image signal processor",
        keyboard: "Backlit Magic Keyboard with Touch ID sensor and ambient light sensor",
        warranty: "1 Year Apple Limited Warranty + 90 Days Complimentary Technical Support"
      },
      useCaseProfile: { gaming: 3.5, productivity: 9.2, editing: 8.5, rendering: 7.0, programming: 9.0, ai: 7.5, streaming: 7.5 }
    },

    // 2. Apple MacBook Air 13" (M3)
    {
      title: "Apple MacBook Air 13.6-inch (M3 chip, 16GB Unified Memory, 512GB SSD) - Space Grey",
      description: "Lean, mean M3 machine. Built on 3nm architecture with hardware-accelerated ray tracing and mesh shading, supporting dual external displays with the laptop lid closed.",
      price: 134900,
      discountPrice: 127900,
      category: macCatId,
      brand: "Apple",
      stock: 28,
      featured: true,
      productType: "laptop",
      images: [
        { url: "/images/laptops/macbook_air_m3_spacegrey_1.jpg", publicId: "macbook_air_m3_spacegrey_1" },
        { url: "/images/laptops/macbook_air_m3_spacegrey_2.jpg", publicId: "macbook_air_m3_spacegrey_2" }
      ],
      rating: 4.9,
      numReviews: 96,
      specifications: {
        brand: "Apple",
        model: "MacBook Air 13 (M3)",
        processor: "Apple M3 (8-core CPU, 10-core GPU, 16-core Neural Engine)",
        processorFamily: "Apple Silicon",
        cpuArchitecture: "ARM64 (3nm TSMC)",
        powerClass: "Fanless Ultra-Efficient (18W)",
        gpu: "Apple M3 Integrated 10-core GPU with Hardware Ray Tracing",
        gpuModel: "Apple M3 10-core",
        gpuVram: 16,
        gpuClass: "Integrated Pro",
        tgp: 18,
        ram: "16GB Unified Memory",
        ramType: "Unified LPDDR5X",
        ramUpgradeability: "Unified On-Package",
        storage: "512GB SSD",
        storageType: "Apple High-Speed NVMe SSD",
        storageInterface: "PCIe Gen4 on-board",
        displaySize: 13.6,
        resolution: "2560 x 1664 Liquid Retina",
        refreshRate: 60,
        panelType: "IPS Liquid Retina Display",
        colorCoverage: "100% DCI-P3 (500 nits, True Tone)",
        battery: "52.6Whr Li-Polymer (up to 18 hours battery life)",
        operatingSystem: "macOS Sequoia",
        weight: "1.24 kg",
        ports: ["MagSafe 3 charging port", "2x Thunderbolt / USB 4 ports (supports up to two external displays)", "3.5mm headphone jack"],
        wifi: "Wi-Fi 6E (802.11ax)",
        bluetooth: "Bluetooth 5.3",
        webcam: "1080p FaceTime HD camera with computational photography",
        keyboard: "Backlit Magic Keyboard with full-height function row and Touch ID",
        warranty: "1 Year Apple Limited Warranty"
      },
      useCaseProfile: { gaming: 5.0, productivity: 9.5, editing: 8.8, rendering: 7.8, programming: 9.3, ai: 8.4, streaming: 8.0 }
    },

    // 3. Apple MacBook Air 15" (M3)
    {
      title: "Apple MacBook Air 15.3-inch (M3 chip, 16GB Unified Memory, 512GB SSD) - Starlight",
      description: "Imposing 15.3-inch Liquid Retina display with an ultra-thin 11.5mm profile, six-speaker sound system with force-cancelling woofers, and relentless M3 battery efficiency.",
      price: 154900,
      discountPrice: 146900,
      category: macCatId,
      brand: "Apple",
      stock: 22,
      featured: false,
      productType: "laptop",
      images: [
        { url: "/images/laptops/macbook_air_15_starlight_1.jpg", publicId: "macbook_air_15_starlight_1" },
        { url: "/images/laptops/macbook_air_15_starlight_2.jpg", publicId: "macbook_air_15_starlight_2" }
      ],
      rating: 4.9,
      numReviews: 64,
      specifications: {
        brand: "Apple",
        model: "MacBook Air 15 (M3)",
        processor: "Apple M3 (8-core CPU, 10-core GPU, 16-core Neural Engine)",
        processorFamily: "Apple Silicon",
        cpuArchitecture: "ARM64 (3nm TSMC)",
        powerClass: "Fanless Ultra-Efficient (18W)",
        gpu: "Apple M3 Integrated 10-core GPU",
        gpuModel: "Apple M3 10-core",
        gpuVram: 16,
        gpuClass: "Integrated Pro",
        tgp: 18,
        ram: "16GB Unified Memory",
        ramType: "Unified LPDDR5X",
        ramUpgradeability: "Unified On-Package",
        storage: "512GB SSD",
        storageType: "Apple High-Speed NVMe SSD",
        storageInterface: "PCIe Gen4 on-board",
        displaySize: 15.3,
        resolution: "2880 x 1864 Liquid Retina",
        refreshRate: 60,
        panelType: "IPS Liquid Retina Display",
        colorCoverage: "100% DCI-P3 (500 nits, True Tone)",
        battery: "66.5Whr Li-Polymer (up to 18 hours battery life)",
        operatingSystem: "macOS Sequoia",
        weight: "1.51 kg",
        ports: ["MagSafe 3 charging port", "2x Thunderbolt / USB 4 ports", "3.5mm headphone jack"],
        wifi: "Wi-Fi 6E (802.11ax)",
        bluetooth: "Bluetooth 5.3",
        webcam: "1080p FaceTime HD camera",
        keyboard: "Backlit Magic Keyboard with Touch ID & Six-speaker sound with Spatial Audio",
        warranty: "1 Year Apple Limited Warranty"
      },
      useCaseProfile: { gaming: 5.0, productivity: 9.6, editing: 9.0, rendering: 8.0, programming: 9.4, ai: 8.4, streaming: 8.2 }
    },

    // 4. Apple MacBook Pro 14" (M4)
    {
      title: "Apple MacBook Pro 14.2-inch (M4 chip, 16GB Unified Memory, 512GB SSD) - Space Black",
      description: "Driven by the M4 processor with 10 CPU cores and 10 GPU cores. Features the Liquid Retina XDR display with up to 1,600 nits peak HDR brightness and 12MP Center Stage camera.",
      price: 169900,
      discountPrice: 164900,
      category: macCatId,
      brand: "Apple",
      stock: 18,
      featured: true,
      productType: "laptop",
      images: [
        { url: "/images/laptops/macbook_pro_14_spaceblack_1.jpg", publicId: "macbook_pro_14_spaceblack_1" },
        { url: "/images/laptops/macbook_pro_14_spaceblack_2.jpg", publicId: "macbook_pro_14_spaceblack_2" }
      ],
      rating: 5.0,
      numReviews: 42,
      specifications: {
        brand: "Apple",
        model: "MacBook Pro 14 (M4)",
        processor: "Apple M4 (10-core CPU with 4 performance cores and 6 efficiency cores)",
        processorFamily: "Apple Silicon",
        cpuArchitecture: "ARM64 (Second Gen 3nm)",
        powerClass: "Active Pro High-Density Cooling (28W)",
        gpu: "Apple M4 10-core GPU (Hardware-accelerated ray tracing)",
        gpuModel: "Apple M4 10-core",
        gpuVram: 16,
        gpuClass: "Integrated Pro",
        tgp: 28,
        ram: "16GB Unified Memory (120GB/s bandwidth)",
        ramType: "Unified LPDDR5X",
        ramUpgradeability: "Unified On-Package",
        storage: "512GB SSD",
        storageType: "Apple Ultra-Speed NVMe SSD",
        storageInterface: "PCIe Gen4 on-board",
        displaySize: 14.2,
        resolution: "3024 x 1964 Liquid Retina XDR",
        refreshRate: 120,
        panelType: "Mini LED Liquid Retina XDR (ProMotion)",
        colorCoverage: "100% DCI-P3 (1600 nits peak HDR, 1000 nits SDR, 1,000,000:1 contrast)",
        battery: "70Whr Li-Polymer (up to 24 hours video playback)",
        operatingSystem: "macOS Sequoia",
        weight: "1.55 kg",
        ports: ["3x Thunderbolt 4 (USB-C) ports", "HDMI port", "SDXC card slot", "MagSafe 3 port", "3.5mm headphone jack"],
        wifi: "Wi-Fi 6E (802.11ax)",
        bluetooth: "Bluetooth 5.3",
        webcam: "12MP Center Stage camera with Desk View support",
        keyboard: "Backlit Magic Keyboard with Touch ID, force touch trackpad & studio-quality 3-mic array",
        warranty: "1 Year Apple Limited Warranty"
      },
      useCaseProfile: { gaming: 6.5, productivity: 9.8, editing: 9.6, rendering: 8.8, programming: 9.8, ai: 9.2, streaming: 9.0 }
    },

    // 5. Apple MacBook Pro 16" (M4 Pro)
    {
      title: "Apple MacBook Pro 16.2-inch (M4 Pro chip, 24GB Unified Memory, 512GB SSD) - Silver",
      description: "Monstrous computing capability for heavy compilation, local LLM execution, and 8K ProRes timelines. Powered by M4 Pro with 14 CPU cores, 20 GPU cores, and Thunderbolt 5 (120 Gbps).",
      price: 249900,
      discountPrice: 242900,
      category: macCatId,
      brand: "Apple",
      stock: 14,
      featured: true,
      productType: "laptop",
      images: [
        { url: "/images/laptops/macbook_pro_16_silver_1.jpg", publicId: "macbook_pro_16_silver_1" },
        { url: "/images/laptops/macbook_pro_16_silver_2.jpg", publicId: "macbook_pro_16_silver_2" }
      ],
      rating: 5.0,
      numReviews: 38,
      specifications: {
        brand: "Apple",
        model: "MacBook Pro 16 (M4 Pro)",
        processor: "Apple M4 Pro (14-core CPU with 10 performance cores and 4 efficiency cores)",
        processorFamily: "Apple Silicon",
        cpuArchitecture: "ARM64 (Second Gen 3nm)",
        powerClass: "Active Pro Dual-Blower Thermal Engine (45W)",
        gpu: "Apple M4 Pro 20-core GPU (273GB/s memory bandwidth)",
        gpuModel: "Apple M4 Pro 20-core",
        gpuVram: 24,
        gpuClass: "Workstation Pro",
        tgp: 45,
        ram: "24GB Unified Memory",
        ramType: "Unified LPDDR5X (273GB/s)",
        ramUpgradeability: "Unified On-Package",
        storage: "512GB SSD",
        storageType: "Apple Ultra-Speed NVMe SSD",
        storageInterface: "PCIe Gen4 on-board",
        displaySize: 16.2,
        resolution: "3456 x 2234 Liquid Retina XDR",
        refreshRate: 120,
        panelType: "Mini LED Liquid Retina XDR (ProMotion)",
        colorCoverage: "100% DCI-P3 (1600 nits peak HDR, 1000 nits sustained SDR)",
        battery: "100Whr Li-Polymer (up to 24 hours battery life)",
        operatingSystem: "macOS Sequoia",
        weight: "2.14 kg",
        ports: ["3x Thunderbolt 5 (USB-C) ports (up to 120Gb/s)", "HDMI port (supports up to 8K @ 60Hz)", "SDXC card slot", "MagSafe 3 port", "3.5mm headphone jack"],
        wifi: "Wi-Fi 6E (802.11ax)",
        bluetooth: "Bluetooth 5.3",
        webcam: "12MP Center Stage camera with 1080p HD video recording",
        keyboard: "Backlit Magic Keyboard with Touch ID, 140W USB-C Power Adapter with fast charge",
        warranty: "1 Year Apple Limited Warranty"
      },
      useCaseProfile: { gaming: 7.5, productivity: 10.0, editing: 10.0, rendering: 9.7, programming: 10.0, ai: 9.8, streaming: 9.5 }
    },

    // 6. ASUS Zenbook 14 OLED (UX3405MA)
    {
      title: "ASUS Zenbook 14 OLED (Intel Core Ultra 7 155H, 16GB LPDDR5X, 1TB SSD, 3K 120Hz OLED) - Ponder Blue",
      description: "Intel Evo certified ultraportable with AI-accelerated Intel Core Ultra 7 155H, 14-inch 3K ASUS Lumina OLED display, 75Whr battery, and aerospace-grade aluminum chassis.",
      price: 122990,
      discountPrice: 104990,
      category: proCatId,
      brand: "ASUS",
      stock: 25,
      featured: true,
      productType: "laptop",
      images: [
        { url: "/images/laptops/asus_zenbook_14_1.jpg", publicId: "asus_zenbook_14_1" },
        { url: "/images/laptops/asus_zenbook_14_2.jpg", publicId: "asus_zenbook_14_2" }
      ],
      rating: 4.8,
      numReviews: 76,
      specifications: {
        brand: "ASUS",
        model: "Zenbook 14 OLED UX3405MA-QD751WS",
        processor: "Intel Core Ultra 7 155H (16 Cores, 22 Threads, up to 4.8 GHz, Intel AI Boost NPU)",
        processorFamily: "Intel Meteor Lake",
        cpuArchitecture: "Intel 4 (6P + 8E + 2LPE)",
        powerClass: "Intel Evo H-Series (28W-64W)",
        gpu: "Intel Arc Graphics (8 Xe Cores)",
        gpuModel: "Intel Arc Graphics",
        gpuVram: 0,
        gpuClass: "Integrated Intel Arc",
        tgp: 28,
        ram: "16GB LPDDR5X-7467MHz",
        ramType: "LPDDR5X",
        ramUpgradeability: "Onboard Dual-Channel",
        storage: "1TB M.2 NVMe PCIe 4.0 SSD",
        storageType: "NVMe M.2 SSD",
        storageInterface: "PCIe 4.0 x4",
        displaySize: 14.0,
        resolution: "2880 x 1800 3K OLED 16:10",
        refreshRate: 120,
        panelType: "ASUS Lumina OLED (0.2ms)",
        colorCoverage: "100% DCI-P3 (500 nits HDR, DisplayHDR True Black 500, PANTONE Validated)",
        battery: "75Whr 4-cell Li-ion (up to 15 hours battery life)",
        operatingSystem: "Windows 11 Home + Office Home & Student 2021",
        weight: "1.20 kg",
        ports: ["2x Thunderbolt 4 Type-C (DP / Power Delivery)", "1x USB 3.2 Gen 1 Type-A", "1x HDMI 2.1 TMDS", "1x 3.5mm Combo Audio Jack"],
        wifi: "Wi-Fi 6E (802.11ax)",
        bluetooth: "Bluetooth 5.3",
        webcam: "FHD camera with IR function for Windows Hello & ambient light sensor",
        keyboard: "Backlit Chiclet Keyboard with ASUS NumberPad 2.0 & Harman Kardon audio",
        warranty: "1 Year Onsite Warranty + 1 Year Accidental Damage Protection"
      },
      useCaseProfile: { gaming: 5.0, productivity: 9.4, editing: 9.0, rendering: 7.8, programming: 9.2, ai: 8.5, streaming: 7.5 }
    },

    // 7. Lenovo ThinkPad E14 Gen 6
    {
      title: "Lenovo ThinkPad E14 Gen 6 (AMD Ryzen 7 7735HS, 16GB DDR5, 512GB SSD, Windows 11 Pro) - Black",
      description: "Business-rugged workhorse engineered with AMD Ryzen 7 7735HS, upgradeable dual-channel DDR5 memory, MIL-STD-810H durability certification, and iconic ThinkPad TrackPoint keyboard.",
      price: 92890,
      discountPrice: 68990,
      category: proCatId,
      brand: "Lenovo",
      stock: 40,
      featured: false,
      productType: "laptop",
      images: [
        { url: "/images/laptops/lenovo_thinkpad_e14_1.jpg", publicId: "lenovo_thinkpad_e14_1" },
        { url: "/images/laptops/lenovo_thinkpad_e14_2.jpg", publicId: "lenovo_thinkpad_e14_2" }
      ],
      rating: 4.7,
      numReviews: 112,
      specifications: {
        brand: "Lenovo",
        model: "ThinkPad E14 Gen 6 (21M30005IG)",
        processor: "AMD Ryzen 7 7735HS (8 Cores, 16 Threads, up to 4.75 GHz, 16MB L3 Cache)",
        processorFamily: "AMD Zen 3+",
        cpuArchitecture: "TSMC 6nm FinFET",
        powerClass: "High-Performance HS (35W-54W)",
        gpu: "AMD Radeon 680M Graphics (12 CUs)",
        gpuModel: "Radeon 680M",
        gpuVram: 0,
        gpuClass: "Integrated AMD RDNA 2",
        tgp: 35,
        ram: "16GB DDR5-4800MHz",
        ramType: "DDR5 SO-DIMM",
        ramUpgradeability: "Upgradeable up to 64GB (2x SO-DIMM slots)",
        storage: "512GB SSD M.2 2242 PCIe 4.0x4 NVMe",
        storageType: "NVMe M.2 SSD",
        storageInterface: "PCIe 4.0 x4 (Dual M.2 SSD slots available)",
        displaySize: 14.0,
        resolution: "1920 x 1200 WUXGA IPS 16:10",
        refreshRate: 60,
        panelType: "Anti-Glare IPS Display",
        colorCoverage: "45% NTSC (300 nits, TÜV Rheinland Low Blue Light)",
        battery: "57Whr (with Rapid Charge: 80% charge in 60min)",
        operatingSystem: "Windows 11 Pro",
        weight: "1.44 kg",
        ports: ["1x USB-C (USB 10Gbps / PD 3.0 / DP 1.4)", "1x USB-C (USB 5Gbps / PD 3.0 / DP 1.4)", "1x USB-A (USB 10Gbps)", "1x USB-A (USB 5Gbps)", "1x HDMI 2.1 TMDS", "1x RJ45 Gigabit Ethernet", "1x Headphone jack"],
        wifi: "Wi-Fi 6E (802.11ax)",
        bluetooth: "Bluetooth 5.3",
        webcam: "1080p FHD Camera with Privacy Shutter",
        keyboard: "Spill-resistant Backlit Keyboard with TrackPoint and TrackPad",
        warranty: "3 Years Premier Onsite Support"
      },
      useCaseProfile: { gaming: 4.5, productivity: 9.3, editing: 7.5, rendering: 7.2, programming: 9.5, ai: 6.8, streaming: 7.0 }
    },

    // 8. Dell Inspiron 14 Plus (7440)
    {
      title: "Dell Inspiron 14 Plus 7440 (Intel Core Ultra 7 155H, 16GB LPDDR5X, 1TB SSD, 2.2K IPS) - Ice Blue",
      description: "Premium enterprise laptop with Intel AI Boost NPU, 14-inch 2.2K 16:10 display, 1TB high-speed NVMe storage, and durable all-metal aluminum chassis.",
      price: 124990,
      discountPrice: 109990,
      category: proCatId,
      brand: "Dell",
      stock: 20,
      featured: false,
      productType: "laptop",
      images: [
        { url: "/images/laptops/dell_inspiron_14_1.jpg", publicId: "dell_inspiron_14_1" },
        { url: "/images/laptops/dell_inspiron_14_2.jpg", publicId: "dell_inspiron_14_2" }
      ],
      rating: 4.7,
      numReviews: 54,
      specifications: {
        brand: "Dell",
        model: "Inspiron 14 Plus (7440)",
        processor: "Intel Core Ultra 7 155H (16 Cores, 22 Threads, up to 4.8 GHz, Intel AI Boost)",
        processorFamily: "Intel Meteor Lake",
        cpuArchitecture: "Intel 4 (6P + 8E + 2LPE)",
        powerClass: "Intel Evo Standard (28W)",
        gpu: "Intel Arc Graphics",
        gpuModel: "Intel Arc Graphics",
        gpuVram: 0,
        gpuClass: "Integrated Intel Arc",
        tgp: 28,
        ram: "16GB LPDDR5X-6400MHz",
        ramType: "LPDDR5X",
        ramUpgradeability: "Onboard Dual-Channel",
        storage: "1TB M.2 PCIe NVMe SSD",
        storageType: "NVMe M.2 SSD",
        storageInterface: "PCIe 4.0 x4",
        displaySize: 14.0,
        resolution: "2240 x 1400 2.2K 16:10",
        refreshRate: 60,
        panelType: "Anti-Glare IPS Display",
        colorCoverage: "100% sRGB (300 nits, ComfortView Plus hardware low blue light)",
        battery: "64Whr 4-cell Integrated",
        operatingSystem: "Windows 11 Home + MS Office Home & Student 2021",
        weight: "1.60 kg",
        ports: ["1x Thunderbolt 4 Type-C (DP / Power Delivery)", "2x USB 3.2 Gen 1 Type-A", "1x HDMI 2.1", "1x MicroSD Card Reader", "1x Headphone/mic combo"],
        wifi: "Intel Wi-Fi 6E AX211",
        bluetooth: "Bluetooth 5.3",
        webcam: "1080p FHD camera with dual-array digital microphones & privacy shutter",
        keyboard: "Ice Blue Backlit Keyboard with Fingerprint Reader integrated into power key",
        warranty: "1 Year Onsite Hardware Service"
      },
      useCaseProfile: { gaming: 4.8, productivity: 9.3, editing: 8.5, rendering: 7.5, programming: 9.2, ai: 8.4, streaming: 7.5 }
    },

    // 9. HP Spectre x360 2-in-1 (14-eu0000TU)
    {
      title: "HP Spectre x360 2-in-1 14-inch (Intel Core Ultra 7 155H, 32GB RAM, 1TB SSD, 2.8K OLED Touch) - Nightfall Black",
      description: "Flagship 360-degree convertible with 2.8K 120Hz IMAX Enhanced OLED touchscreen, 9MP IR AI webcam, 32GB high-speed memory, and included HP Rechargeable Tilt Pen.",
      price: 182790,
      discountPrice: 164999,
      category: proCatId,
      brand: "HP",
      stock: 15,
      featured: true,
      productType: "laptop",
      images: [
        { url: "/images/laptops/hp_spectre_x360_1.jpg", publicId: "hp_spectre_x360_1" },
        { url: "/images/laptops/hp_spectre_x360_2.jpg", publicId: "hp_spectre_x360_2" }
      ],
      rating: 4.9,
      numReviews: 48,
      specifications: {
        brand: "HP",
        model: "Spectre x360 14-eu0000TU",
        processor: "Intel Core Ultra 7 155H (16 Cores, 22 Threads, up to 4.8 GHz)",
        processorFamily: "Intel Meteor Lake",
        cpuArchitecture: "Intel 4 Hybrid",
        powerClass: "Intel Evo Convertible (28W)",
        gpu: "Intel Arc Graphics",
        gpuModel: "Intel Arc Graphics",
        gpuVram: 0,
        gpuClass: "Integrated Intel Arc",
        tgp: 28,
        ram: "32GB LPDDR5X-7467MHz",
        ramType: "LPDDR5X",
        ramUpgradeability: "Onboard (32GB Capacity)",
        storage: "1TB PCIe Gen4 NVMe TLC M.2 SSD",
        storageType: "NVMe TLC M.2 SSD",
        storageInterface: "PCIe 4.0 x4",
        displaySize: 14.0,
        resolution: "2880 x 1800 2.8K OLED Touchscreen",
        refreshRate: 120,
        panelType: "Corning Gorilla Glass NBT OLED (0.2ms)",
        colorCoverage: "100% DCI-P3 (500 nits HDR, IMAX Enhanced, Variable 48-120Hz)",
        battery: "68Whr Li-ion polymer (up to 13 hours battery life)",
        operatingSystem: "Windows 11 Home + Office Home & Student 2021",
        weight: "1.44 kg",
        ports: ["2x Thunderbolt 4 with USB Type-C 40Gbps", "1x USB Type-A 10Gbps (HP Sleep and Charge)", "1x Headphone/mic combo"],
        wifi: "Intel Wi-Fi 7 BE200 (2x2)",
        bluetooth: "Bluetooth 5.4",
        webcam: "HP Wide Vision 9MP IR camera with camera shutter and temporal noise reduction",
        keyboard: "Full-size backlit keyboard + HP Rechargeable MPP2.0 Tilt Pen included",
        warranty: "1 Year Onsite Warranty + 1 Year Accidental Damage Protection"
      },
      useCaseProfile: { gaming: 5.2, productivity: 9.6, editing: 9.4, rendering: 8.0, programming: 9.5, ai: 8.6, streaming: 8.2 }
    },

    // 10. Lenovo Yoga Slim 7x Gen 9 (Copilot+ PC)
    {
      title: "Lenovo Yoga Slim 7x 14.5-inch (Snapdragon X Elite X1E-78-100, 16GB, 1TB SSD, 3K 90Hz OLED) - Cosmic Blue",
      description: "Next-gen Copilot+ PC featuring Qualcomm Snapdragon X Elite with 45 TOPS NPU, vibrant 3K 90Hz PureSight OLED touch panel, and up to 23.5 hours of continuous battery longevity.",
      price: 171890,
      discountPrice: 137990,
      category: proCatId,
      brand: "Lenovo",
      stock: 19,
      featured: true,
      productType: "laptop",
      images: [
        { url: "/images/laptops/lenovo_yoga_slim_7x_1.jpg", publicId: "lenovo_yoga_slim_7x_1" },
        { url: "/images/laptops/lenovo_yoga_slim_7x_2.jpg", publicId: "lenovo_yoga_slim_7x_2" }
      ],
      rating: 4.8,
      numReviews: 32,
      specifications: {
        brand: "Lenovo",
        model: "Yoga Slim 7x 14Q8X9 (83ED002XIN)",
        processor: "Qualcomm Snapdragon X Elite X1E-78-100 (12 Cores, up to 3.4 GHz, 45 TOPS Qualcomm Hexagon NPU)",
        processorFamily: "Qualcomm Oryon ARM",
        cpuArchitecture: "TSMC 4nm ARMv8.7-A",
        powerClass: "Ultra-Efficient ARM (20W-45W)",
        gpu: "Qualcomm Adreno GPU (3.8 TFLOPS)",
        gpuModel: "Qualcomm Adreno GPU",
        gpuVram: 0,
        gpuClass: "Integrated Qualcomm Adreno",
        tgp: 25,
        ram: "16GB LPDDR5X-8448MHz",
        ramType: "LPDDR5X",
        ramUpgradeability: "Onboard Ultra-Fast 8448MHz",
        storage: "1TB SSD M.2 2242 PCIe 4.0x4 NVMe",
        storageType: "NVMe M.2 SSD",
        storageInterface: "PCIe 4.0 x4",
        displaySize: 14.5,
        resolution: "2944 x 1840 3K PureSight OLED Touch",
        refreshRate: 90,
        panelType: "PureSight OLED Touchscreen",
        colorCoverage: "100% DCI-P3 & 100% sRGB (1000 nits peak HDR, DisplayHDR True Black 600, Dolby Vision)",
        battery: "70Whr Li-Polymer (up to 23.5 hours local video playback)",
        operatingSystem: "Windows 11 Home on ARM (Copilot+ PC)",
        weight: "1.28 kg",
        ports: ["3x USB4 Type-C (40Gbps, Power Delivery 3.1, DisplayPort 1.4)"],
        wifi: "Wi-Fi 7 (802.11be)",
        bluetooth: "Bluetooth 5.3",
        webcam: "1080p FHD IR camera with E-shutter & Time-of-Flight sensor",
        keyboard: "Yoga Backlit Keyboard with 1.5mm key travel & 4-speaker Dolby Atmos system",
        warranty: "3 Years Premier Care Onsite Support + 1 Year ADP"
      },
      useCaseProfile: { gaming: 3.5, productivity: 9.8, editing: 8.8, rendering: 7.2, programming: 9.2, ai: 9.6, streaming: 8.5 }
    },

    // =========================================================================
    // 20 GAMING LAPTOPS (Progression from RTX 3050 to RTX 4090 Flagships)
    // =========================================================================

    // 11. Acer Nitro V 15 (RTX 3050 6GB)
    {
      title: "Acer Nitro V 15 ANV15-51 (Intel Core i5-13420H, RTX 3050 6GB, 16GB DDR5, 512GB SSD, 144Hz) - Obsidian Black",
      description: "Entry gaming juggernaut powered by Intel 13th Gen Core i5, NVIDIA GeForce RTX 3050 6GB GDDR6 with 75W TGP, dual-fan cooling, and 144Hz IPS display.",
      price: 79999,
      discountPrice: 61990,
      category: gamingCatId,
      brand: "Acer",
      stock: 45,
      featured: false,
      productType: "laptop",
      images: [
        { url: "/images/laptops/acer_nitro_v15_1.jpg", publicId: "acer_nitro_v15_1" },
        { url: "/images/laptops/acer_nitro_v15_2.jpg", publicId: "acer_nitro_v15_2" }
      ],
      rating: 4.6,
      numReviews: 240,
      specifications: {
        brand: "Acer",
        model: "Nitro V 15 ANV15-51-532J",
        processor: "Intel Core i5-13420H (8 Cores, 12 Threads, up to 4.6 GHz)",
        processorFamily: "Intel 13th Gen Raptor Lake",
        cpuArchitecture: "Intel 7 (4P + 4E)",
        powerClass: "H-Series (45W)",
        gpu: "NVIDIA GeForce RTX 3050 6GB GDDR6 (75W TGP)",
        gpuModel: "GeForce RTX 3050",
        gpuVram: 6,
        gpuClass: "Entry Gaming",
        tgp: 75,
        ram: "16GB DDR5-5200MHz",
        ramType: "DDR5 SO-DIMM",
        ramUpgradeability: "Upgradeable to 32GB (2x SO-DIMM)",
        storage: "512GB PCIe Gen4 NVMe SSD",
        storageType: "NVMe SSD",
        storageInterface: "PCIe 4.0 x4",
        displaySize: 15.6,
        resolution: "1920 x 1080 FHD IPS",
        refreshRate: 144,
        panelType: "IPS SlimBezel Display",
        colorCoverage: "45% NTSC (250 nits brightness)",
        battery: "57Whr 4-cell Li-ion (up to 7 hours usage)",
        operatingSystem: "Windows 11 Home",
        weight: "2.10 kg",
        ports: ["1x Thunderbolt 4 / USB Type-C", "3x USB 3.2 Gen 1 Type-A", "1x HDMI 2.1", "1x RJ-45 Gigabit Ethernet", "1x 3.5mm Headphone Jack"],
        wifi: "Wi-Fi 6 (802.11ax)",
        bluetooth: "Bluetooth 5.1",
        webcam: "720p HD Webcam with Temporal Noise Reduction",
        keyboard: "Backlit Keyboard with Numeric Keypad & NitroSense Key",
        warranty: "1 Year International Travelers Warranty"
      },
      useCaseProfile: { gaming: 6.8, productivity: 7.8, editing: 6.5, rendering: 6.0, programming: 8.0, ai: 5.5, streaming: 6.5 }
    },

    // 12. Lenovo LOQ 15 (RTX 3050 6GB)
    {
      title: "Lenovo LOQ 15 (AMD Ryzen 5 7235HS, RTX 3050 6GB, 16GB DDR5, 512GB SSD, 144Hz 100% sRGB) - Luna Grey",
      description: "Value gaming powerhouse with 85W TGP RTX 3050 6GB, color-accurate 100% sRGB 144Hz IPS display, G-Sync, and Lenovo AI Engine+ with LA1 chip.",
      price: 74990,
      discountPrice: 56990,
      category: gamingCatId,
      brand: "Lenovo",
      stock: 50,
      featured: false,
      productType: "laptop",
      images: [
        { url: "/images/laptops/lenovo_loq_15_1.jpg", publicId: "lenovo_loq_15_1" },
        { url: "/images/laptops/lenovo_loq_15_2.jpg", publicId: "lenovo_loq_15_2" }
      ],
      rating: 4.7,
      numReviews: 180,
      specifications: {
        brand: "Lenovo",
        model: "Lenovo LOQ 15 (83JC0046IN)",
        processor: "AMD Ryzen 5 7235HS (4 Cores, 8 Threads, up to 4.2 GHz)",
        processorFamily: "AMD Zen 3+",
        cpuArchitecture: "TSMC 6nm",
        powerClass: "HS-Series (35W-45W)",
        gpu: "NVIDIA GeForce RTX 3050 6GB GDDR6 (85W TGP)",
        gpuModel: "GeForce RTX 3050",
        gpuVram: 6,
        gpuClass: "Entry Gaming",
        tgp: 85,
        ram: "16GB DDR5-4800MHz",
        ramType: "DDR5 SO-DIMM",
        ramUpgradeability: "Upgradeable to 32GB (2x SO-DIMM)",
        storage: "512GB SSD M.2 2242 PCIe 4.0x4 NVMe",
        storageType: "NVMe SSD",
        storageInterface: "PCIe 4.0 x4 (Dual M.2 Slots)",
        displaySize: 15.6,
        resolution: "1920 x 1080 FHD IPS",
        refreshRate: 144,
        panelType: "Anti-Glare IPS Display",
        colorCoverage: "100% sRGB (300 nits, G-Sync support)",
        battery: "60Whr (Super Rapid Charge Pro 140W)",
        operatingSystem: "Windows 11 Home",
        weight: "2.38 kg",
        ports: ["1x USB-C (10Gbps / PD 140W / DP 1.4)", "3x USB-A (5Gbps)", "1x HDMI 2.1", "1x RJ-45", "1x Audio Combo"],
        wifi: "Wi-Fi 6 (802.11ax)",
        bluetooth: "Bluetooth 5.2",
        webcam: "720p HD with E-shutter",
        keyboard: "White Backlit Gaming Keyboard with 1.5mm key travel",
        warranty: "1 Year Onsite + 1 Year Legion Ultimate Support"
      },
      useCaseProfile: { gaming: 7.0, productivity: 7.5, editing: 6.8, rendering: 6.0, programming: 7.8, ai: 5.5, streaming: 6.5 }
    },

    // 13. ASUS TUF Gaming A15 (RTX 4050 6GB)
    {
      title: "ASUS TUF Gaming A15 FA507NU (AMD Ryzen 7 7735HS, RTX 4050 6GB, 16GB DDR5, 512GB SSD, 144Hz) - Mecha Gray",
      description: "Battlefield-ready gaming rig featuring 140W max TGP RTX 4050 with MUX Switch & NVIDIA Advanced Optimus, large 90Whr battery, and MIL-STD-810H toughness.",
      price: 103990,
      discountPrice: 84990,
      category: gamingCatId,
      brand: "ASUS",
      stock: 32,
      featured: true,
      productType: "laptop",
      images: [
        { url: "/images/laptops/asus_tuf_a15_1.jpg", publicId: "asus_tuf_a15_1" },
        { url: "/images/laptops/asus_tuf_a15_2.jpg", publicId: "asus_tuf_a15_2" }
      ],
      rating: 4.8,
      numReviews: 145,
      specifications: {
        brand: "ASUS",
        model: "TUF Gaming A15 FA507NU-LP084W",
        processor: "AMD Ryzen 7 7735HS (8 Cores, 16 Threads, up to 4.75 GHz)",
        processorFamily: "AMD Zen 3+",
        cpuArchitecture: "TSMC 6nm",
        powerClass: "High-Performance (35W-54W)",
        gpu: "NVIDIA GeForce RTX 4050 6GB GDDR6 (140W Max TGP with Dynamic Boost)",
        gpuModel: "GeForce RTX 4050",
        gpuVram: 6,
        gpuClass: "Mid-Range Gaming",
        tgp: 140,
        ram: "16GB DDR5-4800MHz",
        ramType: "DDR5 SO-DIMM",
        ramUpgradeability: "Upgradeable to 32GB (2x SO-DIMM)",
        storage: "512GB PCIe 4.0 NVMe M.2 SSD",
        storageType: "NVMe SSD",
        storageInterface: "PCIe 4.0 x4",
        displaySize: 15.6,
        resolution: "1920 x 1080 FHD IPS",
        refreshRate: 144,
        panelType: "vIPS Anti-Glare",
        colorCoverage: "100% sRGB (250 nits, G-Sync, MUX Switch + Advanced Optimus)",
        battery: "90Whr 4-cell Li-ion (All-Day Gaming Battery)",
        operatingSystem: "Windows 11 Home",
        weight: "2.20 kg",
        ports: ["1x Type-C USB 4 (DisplayPort)", "1x USB 3.2 Gen 2 Type-C (DP / G-Sync / PD)", "2x USB 3.2 Gen 1 Type-A", "1x HDMI 2.1 FRL", "1x RJ45 Gigabit LAN"],
        wifi: "Wi-Fi 6 (802.11ax)",
        bluetooth: "Bluetooth 5.3",
        webcam: "720p HD Camera",
        keyboard: "1-Zone RGB Backlit Chiclet Keyboard with highlighted WASD",
        warranty: "1 Year Global Warranty"
      },
      useCaseProfile: { gaming: 7.8, productivity: 8.5, editing: 7.8, rendering: 7.2, programming: 8.5, ai: 6.8, streaming: 7.5 }
    },

    // 14. Lenovo LOQ 15IRX9 (RTX 4050 6GB)
    {
      title: "Lenovo LOQ 15IRX9 (Intel Core i5-13450HX, RTX 4050 6GB, 16GB DDR5, 512GB SSD, 144Hz 100% sRGB) - Luna Grey",
      description: "Equipped with desktop-derived Intel Core i5-13450HX processor, 105W TGP RTX 4050, 100% sRGB gaming display, and dual-fan hyperchamber cooling design.",
      price: 106890,
      discountPrice: 79990,
      category: gamingCatId,
      brand: "Lenovo",
      stock: 28,
      featured: false,
      productType: "laptop",
      images: [
        { url: "/images/laptops/lenovo_loq_15irx9_1.jpg", publicId: "lenovo_loq_15irx9_1" },
        { url: "/images/laptops/lenovo_loq_15irx9_2.jpg", publicId: "lenovo_loq_15irx9_2" }
      ],
      rating: 4.8,
      numReviews: 92,
      specifications: {
        brand: "Lenovo",
        model: "LOQ 15IRX9 (83DV00BEIN)",
        processor: "Intel Core i5-13450HX (10 Cores, 16 Threads, up to 4.6 GHz)",
        processorFamily: "Intel Raptor Lake-HX",
        cpuArchitecture: "Intel 7 (6P + 4E)",
        powerClass: "Desktop-Grade HX (55W-157W)",
        gpu: "NVIDIA GeForce RTX 4050 6GB GDDR6 (105W TGP)",
        gpuModel: "GeForce RTX 4050",
        gpuVram: 6,
        gpuClass: "Mid-Range Gaming",
        tgp: 105,
        ram: "16GB DDR5-4800MHz",
        ramType: "DDR5",
        ramUpgradeability: "Upgradeable to 32GB",
        storage: "512GB SSD M.2 2242 PCIe 4.0x4 NVMe",
        storageType: "NVMe SSD",
        storageInterface: "PCIe 4.0 x4",
        displaySize: 15.6,
        resolution: "1920 x 1080 FHD IPS",
        refreshRate: 144,
        panelType: "IPS Anti-Glare",
        colorCoverage: "100% sRGB (300 nits, G-Sync, Advanced Optimus)",
        battery: "60Whr (Rapid Charge Pro)",
        operatingSystem: "Windows 11 Home",
        weight: "2.38 kg",
        ports: ["1x USB-C (10Gbps / PD 140W / DP 1.4)", "3x USB-A 3.2 Gen 1", "1x HDMI 2.1", "1x RJ-45", "1x Audio jack"],
        wifi: "Wi-Fi 6 (802.11ax)",
        bluetooth: "Bluetooth 5.2",
        webcam: "720p HD with E-Shutter",
        keyboard: "1.5mm travel white backlit keyboard with full numpad",
        warranty: "1 Year Onsite + 1 Year ADP included"
      },
      useCaseProfile: { gaming: 7.8, productivity: 8.6, editing: 7.9, rendering: 7.5, programming: 8.7, ai: 7.0, streaming: 7.6 }
    },

    // 15. HP Victus 16 (RTX 4050 6GB)
    {
      title: "HP Victus 16-r0075TX (Intel Core i5-13500HX, RTX 4050 6GB, 16GB DDR5, 512GB SSD, 165Hz) - Performance Blue",
      description: "Generous 16.1-inch 165Hz gaming display powered by 14-core Intel Core i5-13500HX, 120W TGP RTX 4050, OMEN Tempest thermal architecture, and 70Whr fast-charge battery.",
      price: 101500,
      discountPrice: 82990,
      category: gamingCatId,
      brand: "HP",
      stock: 24,
      featured: false,
      productType: "laptop",
      images: [
        { url: "/images/laptops/hp_victus_16_1.jpg", publicId: "hp_victus_16_1" },
        { url: "/images/laptops/hp_victus_16_2.jpg", publicId: "hp_victus_16_2" }
      ],
      rating: 4.7,
      numReviews: 68,
      specifications: {
        brand: "HP",
        model: "Victus Gaming Laptop 16-r0075TX",
        processor: "Intel Core i5-13500HX (14 Cores, 20 Threads, up to 4.7 GHz)",
        processorFamily: "Intel Raptor Lake-HX",
        cpuArchitecture: "Intel 7 (6P + 8E)",
        powerClass: "Enthusiast HX (55W-157W)",
        gpu: "NVIDIA GeForce RTX 4050 6GB GDDR6 (120W TGP)",
        gpuModel: "GeForce RTX 4050",
        gpuVram: 6,
        gpuClass: "Mid-Range Gaming",
        tgp: 120,
        ram: "16GB DDR5-4800MHz",
        ramType: "DDR5",
        ramUpgradeability: "Upgradeable to 32GB (2x SO-DIMM)",
        storage: "512GB PCIe Gen4 NVMe TLC M.2 SSD",
        storageType: "NVMe SSD",
        storageInterface: "PCIe 4.0 x4",
        displaySize: 16.1,
        resolution: "1920 x 1080 FHD IPS",
        refreshRate: 165,
        panelType: "IPS Micro-Edge",
        colorCoverage: "100% sRGB (300 nits, 7ms response time)",
        battery: "70Whr 4-cell Li-ion polymer (Fast charge 50% in 30min)",
        operatingSystem: "Windows 11 Home",
        weight: "2.30 kg",
        ports: ["1x USB Type-C 5Gbps (USB Power Delivery, DisplayPort 1.4)", "3x USB Type-A 5Gbps", "1x HDMI 2.1", "1x RJ-45", "1x Headphone/mic combo"],
        wifi: "MediaTek Wi-Fi 6E MT7922",
        bluetooth: "Bluetooth 5.3",
        webcam: "HP True Vision 1080p FHD camera with temporal noise reduction",
        keyboard: "1-Zone RGB Backlit Keyboard with numeric keypad",
        warranty: "1 Year Onsite Warranty"
      },
      useCaseProfile: { gaming: 7.9, productivity: 8.8, editing: 8.0, rendering: 7.8, programming: 8.8, ai: 7.0, streaming: 7.8 }
    },

    // 16. Acer Predator Helios Neo 16 (RTX 4060 8GB)
    {
      title: "Acer Predator Helios Neo 16 PHN16-72 (Intel Core i7-14700HX, RTX 4060 8GB, 16GB, 1TB, 165Hz WQXGA) - Abyssal Black",
      description: "Full-power 140W RTX 4060 graphics paired with 20-core Intel Core i7-14700HX, laser-etched design, dual 5th Gen AeroBlade 3D metal fans, and 16-inch 2560x1600 IPS display.",
      price: 149999,
      discountPrice: 119990,
      category: gamingCatId,
      brand: "Acer",
      stock: 30,
      featured: true,
      productType: "laptop",
      images: [
        { url: "/images/laptops/acer_predator_helios_neo_1.jpg", publicId: "acer_predator_helios_neo_1" },
        { url: "/images/laptops/acer_predator_helios_neo_2.jpg", publicId: "acer_predator_helios_neo_2" }
      ],
      rating: 4.8,
      numReviews: 88,
      specifications: {
        brand: "Acer",
        model: "Predator Helios Neo 16 PHN16-72-78V1",
        processor: "Intel Core i7-14700HX (20 Cores, 28 Threads, up to 5.5 GHz)",
        processorFamily: "Intel 14th Gen Raptor Lake Refresh",
        cpuArchitecture: "Intel 7 (8P + 12E)",
        powerClass: "High-Power HX (55W-157W)",
        gpu: "NVIDIA GeForce RTX 4060 8GB GDDR6 (140W Max TGP with Dynamic Boost)",
        gpuModel: "GeForce RTX 4060",
        gpuVram: 8,
        gpuClass: "Enthusiast Gaming",
        tgp: 140,
        ram: "16GB DDR5-5600MHz",
        ramType: "DDR5",
        ramUpgradeability: "Upgradeable to 32GB (2x SO-DIMM)",
        storage: "1TB PCIe Gen4 NVMe SSD",
        storageType: "NVMe SSD",
        storageInterface: "PCIe 4.0 x4 (Dual M.2 SSD Slots)",
        displaySize: 16.0,
        resolution: "2560 x 1600 WQXGA 16:10",
        refreshRate: 165,
        panelType: "IPS SlimBezel Display",
        colorCoverage: "100% sRGB (500 nits, 3ms Overdrive, G-Sync, Advanced Optimus)",
        battery: "90Whr 4-cell Li-ion",
        operatingSystem: "Windows 11 Home",
        weight: "2.60 kg",
        ports: ["2x Thunderbolt 4 / USB-C (DisplayPort / USB Charging)", "3x USB 3.2 Gen 2 Type-A", "1x HDMI 2.1", "1x MicroSD Card Reader", "1x Killer Ethernet E2600"],
        wifi: "Killer Wi-Fi 6E AX1675i",
        bluetooth: "Bluetooth 5.3",
        webcam: "720p HD Webcam with Dual Mic Array",
        keyboard: "4-Zone RGB Backlit Keyboard with PredatorSense Key",
        warranty: "1 Year International Travelers Warranty"
      },
      useCaseProfile: { gaming: 8.7, productivity: 9.2, editing: 9.0, rendering: 8.8, programming: 9.4, ai: 8.2, streaming: 8.6 }
    },

    // 17. Lenovo Legion 5i 16 Gen 9 (RTX 4060 8GB)
    {
      title: "Lenovo Legion 5i 16 Gen 9 (Intel Core i7-14650HX, RTX 4060 8GB, 16GB DDR5, 1TB SSD, 165Hz WQXGA) - Luna Grey",
      description: "Refined enthusiast design with 140W TGP RTX 4060, 16-inch 16:10 WQXGA PureSight display, Lenovo Legion Coldfront 5.0 cooling, and TrueStrike RGB keyboard.",
      price: 161890,
      discountPrice: 129990,
      category: gamingCatId,
      brand: "Lenovo",
      stock: 25,
      featured: true,
      productType: "laptop",
      images: [
        { url: "/images/laptops/lenovo_legion_5i_1.jpg", publicId: "lenovo_legion_5i_1" },
        { url: "/images/laptops/lenovo_legion_5i_2.jpg", publicId: "lenovo_legion_5i_2" }
      ],
      rating: 4.9,
      numReviews: 72,
      specifications: {
        brand: "Lenovo",
        model: "Legion 5 16IRX9 (83DG00A0IN)",
        processor: "Intel Core i7-14650HX (16 Cores, 24 Threads, up to 5.2 GHz)",
        processorFamily: "Intel 14th Gen Raptor Lake Refresh",
        cpuArchitecture: "Intel 7 (8P + 8E)",
        powerClass: "High-Power HX (55W-157W)",
        gpu: "NVIDIA GeForce RTX 4060 8GB GDDR6 (140W TGP)",
        gpuModel: "GeForce RTX 4060",
        gpuVram: 8,
        gpuClass: "Enthusiast Gaming",
        tgp: 140,
        ram: "16GB DDR5-5600MHz",
        ramType: "DDR5",
        ramUpgradeability: "Upgradeable to 64GB (2x SO-DIMM)",
        storage: "1TB SSD M.2 2280 PCIe 4.0x4 NVMe",
        storageType: "NVMe SSD",
        storageInterface: "PCIe 4.0 x4",
        displaySize: 16.0,
        resolution: "2560 x 1600 WQXGA 16:10",
        refreshRate: 165,
        panelType: "IPS PureSight Display",
        colorCoverage: "100% sRGB (350 nits, Dolby Vision, G-Sync, TÜV Low Blue Light)",
        battery: "80Whr (Super Rapid Charge Pro 80W in 30min)",
        operatingSystem: "Windows 11 Home",
        weight: "2.30 kg",
        ports: ["1x USB-C (USB 10Gbps / DisplayPort 1.4)", "1x USB-C (USB 10Gbps / PD 140W / DP 1.4)", "3x USB-A (USB 5Gbps)", "1x HDMI 2.1", "1x RJ-45", "1x MicroSD Card Reader"],
        wifi: "Wi-Fi 6E (802.11ax)",
        bluetooth: "Bluetooth 5.2",
        webcam: "1080p FHD with E-shutter",
        keyboard: "4-Zone RGB Backlit Legion TrueStrike Keyboard with 100% anti-ghosting",
        warranty: "1 Year Onsite + 1 Year Legion Ultimate Support + 1 Year ADP"
      },
      useCaseProfile: { gaming: 8.8, productivity: 9.3, editing: 9.0, rendering: 8.7, programming: 9.4, ai: 8.2, streaming: 8.7 }
    },

    // 18. ASUS ROG Zephyrus G16 (RTX 4060 8GB OLED)
    {
      title: "ASUS ROG Zephyrus G16 GU605MV (Intel Core Ultra 7 155H, RTX 4060 8GB, 16GB LPDDR5X, 1TB SSD, 2.5K 240Hz OLED) - Eclipse Gray",
      description: "Ultra-slim 1.49cm CNC aluminum unibody with Slash Lighting, stunning 2.5K 240Hz ROG Nebula OLED display, Intel Core Ultra 7 with AI NPU, and RTX 4060 graphics.",
      price: 219990,
      discountPrice: 174990,
      category: gamingCatId,
      brand: "ASUS",
      stock: 16,
      featured: true,
      productType: "laptop",
      images: [
        { url: "/images/laptops/asus_rog_zephyrus_g16_1.jpg", publicId: "asus_rog_zephyrus_g16_1" },
        { url: "/images/laptops/asus_rog_zephyrus_g16_2.jpg", publicId: "asus_rog_zephyrus_g16_2" }
      ],
      rating: 4.9,
      numReviews: 54,
      specifications: {
        brand: "ASUS",
        model: "ROG Zephyrus G16 GU605MV-QR064W",
        processor: "Intel Core Ultra 7 155H (16 Cores, 22 Threads, up to 4.8 GHz, Intel AI Boost NPU)",
        processorFamily: "Intel Meteor Lake",
        cpuArchitecture: "Intel 4 (6P + 8E + 2LPE)",
        powerClass: "Thin & Light Gaming Ultra (28W-115W)",
        gpu: "NVIDIA GeForce RTX 4060 8GB GDDR6 (100W Max TGP with Dynamic Boost)",
        gpuModel: "GeForce RTX 4060",
        gpuVram: 8,
        gpuClass: "Enthusiast Gaming",
        tgp: 100,
        ram: "16GB LPDDR5X-7467MHz",
        ramType: "LPDDR5X",
        ramUpgradeability: "Onboard Dual-Channel (High Speed)",
        storage: "1TB PCIe 4.0 NVMe M.2 SSD",
        storageType: "NVMe SSD",
        storageInterface: "PCIe 4.0 x4 (Dual M.2 Slots)",
        displaySize: 16.0,
        resolution: "2560 x 1600 2.5K OLED",
        refreshRate: 240,
        panelType: "ROG Nebula OLED (0.2ms)",
        colorCoverage: "100% DCI-P3 (500 nits, VESA DisplayHDR True Black 500, G-Sync)",
        battery: "90Whr 4-cell Li-ion",
        operatingSystem: "Windows 11 Home",
        weight: "1.85 kg",
        ports: ["1x Thunderbolt 4 Type-C (DP / Power Delivery)", "1x USB 3.2 Gen 2 Type-C (DP / Power Delivery)", "2x USB 3.2 Gen 2 Type-A", "1x HDMI 2.1 FRL", "1x SD Card Reader (UHS-II)"],
        wifi: "Wi-Fi 6E (802.11ax)",
        bluetooth: "Bluetooth 5.3",
        webcam: "1080p FHD IR Camera for Windows Hello",
        keyboard: "1-Zone RGB Backlit Keyboard with Slash Lighting on CNC Aluminum Lid",
        warranty: "1 Year Global Warranty + 1 Year ADP"
      },
      useCaseProfile: { gaming: 8.6, productivity: 9.5, editing: 9.6, rendering: 8.5, programming: 9.5, ai: 8.6, streaming: 8.6 }
    },

    // 19. HP OMEN 16 (RTX 4060 8GB)
    {
      title: "HP OMEN 16-wf1025TX (Intel Core i7-14700HX, RTX 4060 8GB, 16GB DDR5, 1TB SSD, 165Hz FHD) - Shadow Black",
      description: "Clean aesthetic esports laptop equipped with 20-core Intel Core i7-14700HX, 140W TGP RTX 4060, OMEN Tempest Cooling with IR thermopile sensor, and dual Thunderbolt 4 ports.",
      price: 139990,
      discountPrice: 117990,
      category: gamingCatId,
      brand: "HP",
      stock: 26,
      featured: false,
      productType: "laptop",
      images: [
        { url: "/images/laptops/hp_omen_16_1.jpg", publicId: "hp_omen_16_1" },
        { url: "/images/laptops/hp_omen_16_2.jpg", publicId: "hp_omen_16_2" }
      ],
      rating: 4.8,
      numReviews: 61,
      specifications: {
        brand: "HP",
        model: "OMEN Gaming Laptop 16-wf1025TX",
        processor: "Intel Core i7-14700HX (20 Cores, 28 Threads, up to 5.5 GHz)",
        processorFamily: "Intel 14th Gen Raptor Lake Refresh",
        cpuArchitecture: "Intel 7 (8P + 12E)",
        powerClass: "High-Power HX (55W-157W)",
        gpu: "NVIDIA GeForce RTX 4060 8GB GDDR6 (140W TGP)",
        gpuModel: "GeForce RTX 4060",
        gpuVram: 8,
        gpuClass: "Enthusiast Gaming",
        tgp: 140,
        ram: "16GB DDR5-5600MHz",
        ramType: "DDR5",
        ramUpgradeability: "Upgradeable to 32GB (2x SO-DIMM)",
        storage: "1TB PCIe Gen4 NVMe TLC M.2 SSD",
        storageType: "NVMe SSD",
        storageInterface: "PCIe 4.0 x4",
        displaySize: 16.1,
        resolution: "1920 x 1080 FHD IPS",
        refreshRate: 165,
        panelType: "Anti-Glare IPS",
        colorCoverage: "100% sRGB (300 nits, 7ms, Low Blue Light)",
        battery: "83Whr 6-cell Li-ion polymer",
        operatingSystem: "Windows 11 Home",
        weight: "2.39 kg",
        ports: ["2x Thunderbolt 4 with USB Type-C 40Gbps", "2x USB Type-A 5Gbps", "1x HDMI 2.1", "1x RJ-45 Gigabit Ethernet", "1x Headphone/mic combo"],
        wifi: "Intel Wi-Fi 6E AX211",
        bluetooth: "Bluetooth 5.3",
        webcam: "HP True Vision 1080p FHD camera with temporal noise reduction",
        keyboard: "4-Zone RGB Backlit Keyboard with 26-key rollover anti-ghosting",
        warranty: "1 Year Onsite Warranty"
      },
      useCaseProfile: { gaming: 8.7, productivity: 9.3, editing: 8.8, rendering: 8.8, programming: 9.4, ai: 8.2, streaming: 8.7 }
    },

    // 20. ASUS ROG Strix G16 (RTX 4070 8GB)
    {
      title: "ASUS ROG Strix G16 G614JIR (Intel Core i9-14900HX, RTX 4070 8GB, 16GB DDR5, 1TB SSD, 240Hz QHD+) - Eclipse Gray",
      description: "Esports dominance with 24-core Intel Core i9-14900HX, 140W RTX 4070, ROG Nebula 240Hz 3ms QHD+ display with 100% DCI-P3, and Conductonaut Extreme liquid metal cooling.",
      price: 214990,
      discountPrice: 179990,
      category: gamingCatId,
      brand: "ASUS",
      stock: 20,
      featured: true,
      productType: "laptop",
      images: [
        { url: "/images/laptops/asus_rog_strix_g16_1.jpg", publicId: "asus_rog_strix_g16_1" },
        { url: "/images/laptops/asus_rog_strix_g16_2.jpg", publicId: "asus_rog_strix_g16_2" }
      ],
      rating: 4.9,
      numReviews: 79,
      specifications: {
        brand: "ASUS",
        model: "ROG Strix G16 G614JIR-N4062W",
        processor: "Intel Core i9-14900HX (24 Cores, 32 Threads, up to 5.8 GHz)",
        processorFamily: "Intel 14th Gen Raptor Lake Refresh",
        cpuArchitecture: "Intel 7 (8P + 16E)",
        powerClass: "Flagship HX (55W-175W)",
        gpu: "NVIDIA GeForce RTX 4070 8GB GDDR6 (140W Max TGP with Dynamic Boost)",
        gpuModel: "GeForce RTX 4070",
        gpuVram: 8,
        gpuClass: "High-Performance Gaming",
        tgp: 140,
        ram: "16GB DDR5-5600MHz",
        ramType: "DDR5 SO-DIMM",
        ramUpgradeability: "Upgradeable to 32GB (2x SO-DIMM)",
        storage: "1TB PCIe 4.0 NVMe M.2 SSD",
        storageType: "NVMe SSD",
        storageInterface: "PCIe 4.0 x4 (Dual M.2 Slots)",
        displaySize: 16.0,
        resolution: "2560 x 1600 QHD+ 16:10",
        refreshRate: 240,
        panelType: "ROG Nebula Display (3ms)",
        colorCoverage: "100% DCI-P3 (500 nits, Pantone Validated, G-Sync)",
        battery: "90Whr 4-cell Li-ion (Fast charge to 50% in 30min)",
        operatingSystem: "Windows 11 Home",
        weight: "2.50 kg",
        ports: ["1x Thunderbolt 4 Type-C (DP)", "1x USB 3.2 Gen 2 Type-C (DP / Power Delivery / G-Sync)", "2x USB 3.2 Gen 2 Type-A", "1x HDMI 2.1 FRL", "1x 2.5G LAN RJ-45"],
        wifi: "Wi-Fi 6E (802.11ax)",
        bluetooth: "Bluetooth 5.3",
        webcam: "720p HD Camera",
        keyboard: "4-Zone RGB Backlit Chiclet Keyboard with Overstroke technology",
        warranty: "1 Year Global Warranty"
      },
      useCaseProfile: { gaming: 9.2, productivity: 9.6, editing: 9.4, rendering: 9.3, programming: 9.7, ai: 8.8, streaming: 9.2 }
    },

    // 21. Lenovo Legion Pro 5 16 (RTX 4070 8GB)
    {
      title: "Lenovo Legion Pro 5 16IRX9 (Intel Core i9-14900HX, RTX 4070 8GB, 32GB DDR5, 1TB SSD, 240Hz WQXGA) - Onyx Grey",
      description: "High-tier competitive battlestation featuring 32GB DDR5, 140W RTX 4070, 240Hz 500-nit PureSight display with DisplayHDR 400, and Lenovo AI Engine+ with LA1 chip tuning.",
      price: 234890,
      discountPrice: 189990,
      category: gamingCatId,
      brand: "Lenovo",
      stock: 18,
      featured: true,
      productType: "laptop",
      images: [
        { url: "/images/laptops/lenovo_legion_pro_5_1.jpg", publicId: "lenovo_legion_pro_5_1" },
        { url: "/images/laptops/lenovo_legion_pro_5_2.jpg", publicId: "lenovo_legion_pro_5_2" }
      ],
      rating: 4.9,
      numReviews: 65,
      specifications: {
        brand: "Lenovo",
        model: "Legion Pro 5 16IRX9 (83DF003PIN)",
        processor: "Intel Core i9-14900HX (24 Cores, 32 Threads, up to 5.8 GHz)",
        processorFamily: "Intel 14th Gen Raptor Lake Refresh",
        cpuArchitecture: "Intel 7 (8P + 16E)",
        powerClass: "Flagship HX (55W-175W)",
        gpu: "NVIDIA GeForce RTX 4070 8GB GDDR6 (140W TGP)",
        gpuModel: "GeForce RTX 4070",
        gpuVram: 8,
        gpuClass: "High-Performance Gaming",
        tgp: 140,
        ram: "32GB DDR5-5600MHz (2x16GB)",
        ramType: "DDR5",
        ramUpgradeability: "Upgradeable to 64GB (2x SO-DIMM)",
        storage: "1TB SSD M.2 2280 PCIe 4.0x4 NVMe",
        storageType: "NVMe SSD",
        storageInterface: "PCIe 4.0 x4 (Dual M.2 Slots)",
        displaySize: 16.0,
        resolution: "2560 x 1600 WQXGA 16:10",
        refreshRate: 240,
        panelType: "IPS PureSight Gaming Display",
        colorCoverage: "100% DCI-P3 (500 nits, DisplayHDR 400, G-Sync, X-Rite factory calibrated)",
        battery: "80Whr (Super Rapid Charge Pro 140W)",
        operatingSystem: "Windows 11 Home",
        weight: "2.50 kg",
        ports: ["1x USB-C (USB 10Gbps / DisplayPort 1.4)", "1x USB-C (USB 10Gbps / PD 140W / DP 1.4)", "4x USB-A (USB 5Gbps)", "1x HDMI 2.1", "1x RJ-45", "1x Audio jack"],
        wifi: "Wi-Fi 6E (802.11ax)",
        bluetooth: "Bluetooth 5.2",
        webcam: "1080p FHD with E-shutter",
        keyboard: "4-Zone RGB Backlit Legion TrueStrike Keyboard",
        warranty: "1 Year Onsite + 1 Year Legion Ultimate Support + 1 Year ADP"
      },
      useCaseProfile: { gaming: 9.3, productivity: 9.8, editing: 9.6, rendering: 9.5, programming: 9.8, ai: 9.0, streaming: 9.3 }
    },

    // 22. MSI Katana 15 (RTX 4070 8GB)
    {
      title: "MSI Katana 15 B13VGK (Intel Core i7-13620H, RTX 4070 8GB, 16GB DDR5, 1TB SSD, 144Hz FHD) - Black",
      description: "Aggressive price-to-performance RTX 4070 gaming weapon equipped with Intel Core i7-13620H, Cooler Boost 5 with shared heat pipe architecture, and 4-zone RGB keyboard.",
      price: 149990,
      discountPrice: 119990,
      category: gamingCatId,
      brand: "MSI",
      stock: 22,
      featured: false,
      productType: "laptop",
      images: [
        { url: "/images/laptops/msi_katana_15_1.jpg", publicId: "msi_katana_15_1" },
        { url: "/images/laptops/msi_katana_15_2.jpg", publicId: "msi_katana_15_2" }
      ],
      rating: 4.6,
      numReviews: 58,
      specifications: {
        brand: "MSI",
        model: "Katana 15 B13VGK-1208IN",
        processor: "Intel Core i7-13620H (10 Cores, 16 Threads, up to 4.9 GHz)",
        processorFamily: "Intel 13th Gen Raptor Lake",
        cpuArchitecture: "Intel 7 (6P + 4E)",
        powerClass: "H-Series (45W-115W)",
        gpu: "NVIDIA GeForce RTX 4070 8GB GDDR6 (105W TGP with Dynamic Boost)",
        gpuModel: "GeForce RTX 4070",
        gpuVram: 8,
        gpuClass: "High-Performance Gaming",
        tgp: 105,
        ram: "16GB DDR5-5200MHz",
        ramType: "DDR5",
        ramUpgradeability: "Upgradeable to 64GB (2x slots)",
        storage: "1TB NVMe PCIe Gen4 SSD",
        storageType: "NVMe SSD",
        storageInterface: "PCIe 4.0 x4",
        displaySize: 15.6,
        resolution: "1920 x 1080 FHD IPS-Level",
        refreshRate: 144,
        panelType: "IPS-Level Anti-Glare",
        colorCoverage: "45% NTSC (250 nits)",
        battery: "53.5Whr 3-cell Li-Polymer",
        operatingSystem: "Windows 11 Home",
        weight: "2.25 kg",
        ports: ["1x Type-C (USB 3.2 Gen 1 / DP)", "2x Type-A USB 3.2 Gen 1", "1x Type-A USB 2.0", "1x HDMI 2.1 (8K @ 60Hz / 4K @ 120Hz)", "1x RJ45 Gigabit LAN"],
        wifi: "Intel Wi-Fi 6 AX201",
        bluetooth: "Bluetooth 5.2",
        webcam: "720p HD Camera",
        keyboard: "4-Zone RGB Gaming Keyboard with translucent WASD keys",
        warranty: "2 Years Carry-in Warranty"
      },
      useCaseProfile: { gaming: 9.0, productivity: 8.8, editing: 8.2, rendering: 8.4, programming: 9.0, ai: 8.5, streaming: 8.6 }
    },

    // 23. Dell Alienware m16 R2 (RTX 4070 8GB)
    {
      title: "Dell Alienware m16 R2 (Intel Core Ultra 7 155H, RTX 4070 8GB, 16GB DDR5, 1TB SSD, 240Hz QHD+) - Dark Metallic Moon",
      description: "Iconic Alienware engineering redesigned 15% smaller with 140W RTX 4070, Stealth Mode key for instant quiet mode, Cryo-tech thermal architecture, and 240Hz QHD+ display.",
      price: 222990,
      discountPrice: 184990,
      category: gamingCatId,
      brand: "Dell",
      stock: 14,
      featured: true,
      productType: "laptop",
      images: [
        { url: "/images/laptops/dell_alienware_m16_1.jpg", publicId: "dell_alienware_m16_1" },
        { url: "/images/laptops/dell_alienware_m16_2.jpg", publicId: "dell_alienware_m16_2" }
      ],
      rating: 4.8,
      numReviews: 44,
      specifications: {
        brand: "Dell",
        model: "Alienware m16 R2 (Dark Metallic Moon)",
        processor: "Intel Core Ultra 7 155H (16 Cores, 22 Threads, up to 4.8 GHz, Intel AI Boost NPU)",
        processorFamily: "Intel Meteor Lake",
        cpuArchitecture: "Intel 4 (6P + 8E + 2LPE)",
        powerClass: "Alienware Cryo-tech (45W-115W)",
        gpu: "NVIDIA GeForce RTX 4070 8GB GDDR6 (140W TGP with Dynamic Boost)",
        gpuModel: "GeForce RTX 4070",
        gpuVram: 8,
        gpuClass: "High-Performance Gaming",
        tgp: 140,
        ram: "16GB DDR5-5600MHz (2x8GB)",
        ramType: "DDR5",
        ramUpgradeability: "Upgradeable to 64GB (2x SO-DIMM)",
        storage: "1TB M.2 PCIe NVMe SSD",
        storageType: "NVMe SSD",
        storageInterface: "PCIe 4.0 x4",
        displaySize: 16.0,
        resolution: "2560 x 1600 QHD+ 16:10",
        refreshRate: 240,
        panelType: "ComfortView Plus WVA (3ms)",
        colorCoverage: "100% sRGB (300 nits, G-Sync, Advanced Optimus)",
        battery: "90Whr 6-cell Integrated",
        operatingSystem: "Windows 11 Home",
        weight: "2.61 kg",
        ports: ["1x Thunderbolt 4 / USB-C (DisplayPort 1.4 / 15W PD)", "1x USB-C 3.2 Gen 2 (DisplayPort 1.4 / 15W PD)", "2x USB-A 3.2 Gen 1", "1x HDMI 2.1", "1x MicroSD Card Slot", "1x RJ-45 2.5Gbps"],
        wifi: "Intel Killer Wi-Fi 7 BE1750 (2x2)",
        bluetooth: "Bluetooth 5.4",
        webcam: "1080p FHD RGB+IR camera with dual-array microphones",
        keyboard: "AlienFX 1-Zone RGB Backlit Keyboard with Stealth Mode hotkey",
        warranty: "1 Year Premium Support and Onsite Service"
      },
      useCaseProfile: { gaming: 9.2, productivity: 9.4, editing: 9.2, rendering: 9.0, programming: 9.5, ai: 8.8, streaming: 9.0 }
    },

    // 24. ASUS ROG Strix SCAR 16 (RTX 4080 12GB Mini LED)
    {
      title: "ASUS ROG Strix SCAR 16 G634JZ (Intel Core i9-13980HX, RTX 4080 12GB, 32GB DDR5, 1TB SSD, 240Hz Mini LED) - Off Black",
      description: "Apex esports desktop replacement featuring 175W RTX 4080 12GB, 16-inch ROG Nebula HDR Mini LED display with 1100 nits peak brightness and 1024 local dimming zones.",
      price: 329990,
      discountPrice: 269990,
      category: gamingCatId,
      brand: "ASUS",
      stock: 12,
      featured: true,
      productType: "laptop",
      images: [
        { url: "/images/laptops/asus_rog_strix_scar_16_1.jpg", publicId: "asus_rog_strix_scar_16_1" },
        { url: "/images/laptops/asus_rog_strix_scar_16_2.jpg", publicId: "asus_rog_strix_scar_16_2" }
      ],
      rating: 5.0,
      numReviews: 52,
      specifications: {
        brand: "ASUS",
        model: "ROG Strix SCAR 16 G634JZ-NM057W",
        processor: "Intel Core i9-13980HX (24 Cores, 32 Threads, up to 5.6 GHz)",
        processorFamily: "Intel 13th Gen Raptor Lake-HX",
        cpuArchitecture: "Intel 7 (8P + 16E)",
        powerClass: "Desktop-Class HX (55W-175W)",
        gpu: "NVIDIA GeForce RTX 4080 12GB GDDR6 (175W Max TGP with Dynamic Boost)",
        gpuModel: "GeForce RTX 4080",
        gpuVram: 12,
        gpuClass: "Enthusiast Flagship Gaming",
        tgp: 175,
        ram: "32GB DDR5-4800MHz (2x16GB)",
        ramType: "DDR5",
        ramUpgradeability: "Upgradeable to 64GB (2x SO-DIMM)",
        storage: "1TB PCIe 4.0 NVMe M.2 Performance SSD",
        storageType: "NVMe Performance SSD",
        storageInterface: "PCIe 4.0 x4 (Dual M.2 Slots)",
        displaySize: 16.0,
        resolution: "2560 x 1600 QHD+ 16:10",
        refreshRate: 240,
        panelType: "ROG Nebula HDR Mini LED (3ms)",
        colorCoverage: "100% DCI-P3 (1100 nits peak HDR, 1024 local dimming zones, G-Sync)",
        battery: "90Whr 4-cell Li-ion (Fast charge to 50% in 30min)",
        operatingSystem: "Windows 11 Home",
        weight: "2.50 kg",
        ports: ["1x Thunderbolt 4 Type-C (DP / G-Sync)", "1x USB 3.2 Gen 2 Type-C (DP / Power Delivery / G-Sync)", "2x USB 3.2 Gen 2 Type-A", "1x HDMI 2.1 FRL", "1x 2.5G LAN RJ-45"],
        wifi: "Wi-Fi 6E (802.11ax)",
        bluetooth: "Bluetooth 5.3",
        webcam: "720p HD Camera",
        keyboard: "Per-Key RGB Backlit Keyboard with Conductonaut Extreme Liquid Metal on CPU & GPU",
        warranty: "1 Year Global Warranty"
      },
      useCaseProfile: { gaming: 9.8, productivity: 9.8, editing: 9.8, rendering: 9.8, programming: 9.8, ai: 9.5, streaming: 9.7 }
    },

    // 25. Lenovo Legion Pro 7i 16 (RTX 4080 12GB)
    {
      title: "Lenovo Legion Pro 7i 16IRX9H (Intel Core i9-14900HX, RTX 4080 12GB, 32GB DDR5, 1TB SSD, 240Hz WQXGA) - Eclipse Black",
      description: "Esports tournament flagship powered by 24-core i9-14900HX, 175W RTX 4080, Legion Coldfront: Vapor Chamber cooling with liquid metal, and maximum 99.99Whr airline-limit battery.",
      price: 346890,
      discountPrice: 279990,
      category: gamingCatId,
      brand: "Lenovo",
      stock: 15,
      featured: true,
      productType: "laptop",
      images: [
        { url: "/images/laptops/lenovo_legion_pro_7i_1.jpg", publicId: "lenovo_legion_pro_7i_1" },
        { url: "/images/laptops/lenovo_legion_pro_7i_2.jpg", publicId: "lenovo_legion_pro_7i_2" }
      ],
      rating: 5.0,
      numReviews: 49,
      specifications: {
        brand: "Lenovo",
        model: "Legion Pro 7 16IRX9H (83DE001VIN)",
        processor: "Intel Core i9-14900HX (24 Cores, 32 Threads, up to 5.8 GHz)",
        processorFamily: "Intel 14th Gen Raptor Lake Refresh",
        cpuArchitecture: "Intel 7 (8P + 16E)",
        powerClass: "Extreme HX (55W-175W)",
        gpu: "NVIDIA GeForce RTX 4080 12GB GDDR6 (175W TGP)",
        gpuModel: "GeForce RTX 4080",
        gpuVram: 12,
        gpuClass: "Enthusiast Flagship Gaming",
        tgp: 175,
        ram: "32GB DDR5-5600MHz (2x16GB)",
        ramType: "DDR5",
        ramUpgradeability: "Upgradeable to 64GB (2x SO-DIMM)",
        storage: "1TB SSD M.2 2280 PCIe 4.0x4 NVMe",
        storageType: "NVMe SSD",
        storageInterface: "PCIe 4.0 x4 (Dual M.2 Slots)",
        displaySize: 16.0,
        resolution: "2560 x 1600 WQXGA 16:10",
        refreshRate: 240,
        panelType: "IPS PureSight Gaming Display",
        colorCoverage: "100% DCI-P3 (500 nits, DisplayHDR 400, G-Sync, X-Rite factory calibrated)",
        battery: "99.99Whr (Maximum Airline Allowable Battery Capacity)",
        operatingSystem: "Windows 11 Home",
        weight: "2.62 kg",
        ports: ["1x Thunderbolt 4 / USB-C (DisplayPort 1.4)", "1x USB-C (USB 10Gbps / PD 140W / DP 1.4)", "4x USB-A (USB 5Gbps)", "1x HDMI 2.1", "1x RJ-45 Gigabit Ethernet", "1x Headphone/mic combo"],
        wifi: "Wi-Fi 6E (802.11ax)",
        bluetooth: "Bluetooth 5.2",
        webcam: "1080p FHD with E-shutter",
        keyboard: "Per-Key RGB Backlit Legion TrueStrike Keyboard with Legion Coldfront Vapor Chamber",
        warranty: "1 Year Onsite + 1 Year Legion Ultimate Support + 1 Year ADP"
      },
      useCaseProfile: { gaming: 9.8, productivity: 9.9, editing: 9.8, rendering: 9.8, programming: 9.9, ai: 9.6, streaming: 9.8 }
    },

    // 26. Acer Predator Helios 16 (RTX 4080 12GB Mini LED)
    {
      title: "Acer Predator Helios 16 PH16-72 (Intel Core i9-14900HX, RTX 4080 12GB, 32GB, 2TB SSD, 240Hz Mini LED) - Black",
      description: "Flagship gaming powerhouse armed with 24-core i9-14900HX, 175W RTX 4080, 2TB high-speed PCIe Gen4 storage, MagClick mechanical switches, and 1000-nit Mini LED panel.",
      price: 319999,
      discountPrice: 259990,
      category: gamingCatId,
      brand: "Acer",
      stock: 10,
      featured: true,
      productType: "laptop",
      images: [
        { url: "/images/laptops/acer_predator_helios_16_1.jpg", publicId: "acer_predator_helios_16_1" },
        { url: "/images/laptops/acer_predator_helios_16_2.jpg", publicId: "acer_predator_helios_16_2" }
      ],
      rating: 4.9,
      numReviews: 36,
      specifications: {
        brand: "Acer",
        model: "Predator Helios 16 PH16-72-98J4",
        processor: "Intel Core i9-14900HX (24 Cores, 32 Threads, up to 5.8 GHz)",
        processorFamily: "Intel 14th Gen Raptor Lake Refresh",
        cpuArchitecture: "Intel 7 (8P + 16E)",
        powerClass: "High-Power HX (55W-175W)",
        gpu: "NVIDIA GeForce RTX 4080 12GB GDDR6 (175W TGP)",
        gpuModel: "GeForce RTX 4080",
        gpuVram: 12,
        gpuClass: "Enthusiast Flagship Gaming",
        tgp: 175,
        ram: "32GB DDR5-5600MHz (2x16GB)",
        ramType: "DDR5",
        ramUpgradeability: "Upgradeable to 64GB (2x SO-DIMM)",
        storage: "2TB PCIe Gen4 NVMe SSD",
        storageType: "NVMe SSD",
        storageInterface: "PCIe 4.0 x4 (Dual M.2 Slots)",
        displaySize: 16.0,
        resolution: "2560 x 1600 WQXGA Mini LED",
        refreshRate: 240,
        panelType: "Mini LED Display",
        colorCoverage: "100% DCI-P3 (1000 nits, VESA DisplayHDR 1000, 3ms, G-Sync)",
        battery: "90Whr 4-cell Li-ion",
        operatingSystem: "Windows 11 Home",
        weight: "2.70 kg",
        ports: ["2x Thunderbolt 4 / USB-C", "3x USB 3.2 Gen 2 Type-A", "1x HDMI 2.1", "1x MicroSD Card Reader", "1x Killer Ethernet E3100G 2.5G"],
        wifi: "Killer Wi-Fi 7 BE1750",
        bluetooth: "Bluetooth 5.4",
        webcam: "1080p FHD Webcam with temporal noise reduction",
        keyboard: "Per-Key RGB MagClick Mechanical Switches with swappable WASD keycaps",
        warranty: "1 Year International Travelers Warranty"
      },
      useCaseProfile: { gaming: 9.8, productivity: 9.8, editing: 9.8, rendering: 9.8, programming: 9.8, ai: 9.5, streaming: 9.7 }
    },

    // 27. ASUS ROG Strix SCAR 18 (RTX 4090 16GB)
    {
      title: "ASUS ROG Strix SCAR 18 G834JYR (Intel Core i9-14900HX, RTX 4090 16GB, 32GB DDR5, 2TB RAID 0 SSD, 2.5K 240Hz Mini LED) - Off Black",
      description: "Colossal 18-inch desktop replacer powered by full 175W RTX 4090 16GB, 24-core i9-14900HX, 2TB PCIe 4.0 RAID 0 array, Tri-Fan cooling with liquid metal, and 2.5K 240Hz Mini LED display.",
      price: 419990,
      discountPrice: 359990,
      category: gamingCatId,
      brand: "ASUS",
      stock: 8,
      featured: true,
      productType: "laptop",
      images: [
        { url: "/images/laptops/asus_rog_strix_scar_18_1.jpg", publicId: "asus_rog_strix_scar_18_1" },
        { url: "/images/laptops/asus_rog_strix_scar_18_2.jpg", publicId: "asus_rog_strix_scar_18_2" }
      ],
      rating: 5.0,
      numReviews: 28,
      specifications: {
        brand: "ASUS",
        model: "ROG Strix SCAR 18 G834JYR-R6001W",
        processor: "Intel Core i9-14900HX (24 Cores, 32 Threads, up to 5.8 GHz)",
        processorFamily: "Intel 14th Gen Raptor Lake Refresh",
        cpuArchitecture: "Intel 7 (8P + 16E)",
        powerClass: "Desktop-Replacement Extreme (65W-240W Combined)",
        gpu: "NVIDIA GeForce RTX 4090 16GB GDDR6 (175W Max TGP with Dynamic Boost, ROG Boost: 2090MHz)",
        gpuModel: "GeForce RTX 4090",
        gpuVram: 16,
        gpuClass: "Ultra Flagship Gaming",
        tgp: 175,
        ram: "32GB DDR5-5600MHz (2x16GB)",
        ramType: "DDR5",
        ramUpgradeability: "Upgradeable to 64GB (2x SO-DIMM)",
        storage: "2TB (1TB + 1TB) PCIe 4.0 NVMe M.2 Performance SSD in RAID 0",
        storageType: "NVMe RAID 0",
        storageInterface: "PCIe 4.0 x4 (Dual M.2 in RAID 0)",
        displaySize: 18.0,
        resolution: "2560 x 1600 2.5K ROG Nebula HDR",
        refreshRate: 240,
        panelType: "Mini LED Display (>2000 dimming zones)",
        colorCoverage: "100% DCI-P3 (1100 nits peak HDR, 3ms, G-Sync, Dolby Vision)",
        battery: "90Whr 4-cell Li-ion (330W Adapter)",
        operatingSystem: "Windows 11 Home",
        weight: "3.10 kg",
        ports: ["1x Thunderbolt 4 Type-C (DP / G-Sync)", "1x USB 3.2 Gen 2 Type-C (DP / Power Delivery / G-Sync)", "2x USB 3.2 Gen 2 Type-A", "1x HDMI 2.1 FRL", "1x 2.5G LAN RJ-45"],
        wifi: "Wi-Fi 6E (802.11ax)",
        bluetooth: "Bluetooth 5.3",
        webcam: "720p HD Camera",
        keyboard: "Per-Key RGB Backlit Chiclet Keyboard with full numeric keypad & Conductonaut Extreme liquid metal",
        warranty: "1 Year Global Warranty"
      },
      useCaseProfile: { gaming: 10.0, productivity: 10.0, editing: 10.0, rendering: 10.0, programming: 10.0, ai: 10.0, streaming: 10.0 }
    },

    // 28. MSI Titan 18 HX (RTX 4090 16GB)
    {
      title: "MSI Titan 18 HX A14VIG (Intel Core i9-14900HX, RTX 4090 16GB, 64GB DDR5, 4TB SSD, 18\" 4K 120Hz Mini LED) - Core Black",
      description: "The pinnacle of portable computational supremacy. Combines 270W MSI OverBoost Ultra combined wattage, 4x DDR5 slots (up to 192GB), 4TB NVMe SSD array, Cherry MX mechanical switches, and 18-inch 4K 120Hz Mini LED panel.",
      price: 599990,
      discountPrice: 499990,
      category: gamingCatId,
      brand: "MSI",
      stock: 5,
      featured: true,
      productType: "laptop",
      images: [
        { url: "/images/laptops/msi_titan_18_hx_1.jpg", publicId: "msi_titan_18_hx_1" },
        { url: "/images/laptops/msi_titan_18_hx_2.jpg", publicId: "msi_titan_18_hx_2" }
      ],
      rating: 5.0,
      numReviews: 19,
      specifications: {
        brand: "MSI",
        model: "Titan 18 HX A14VIG-069IN",
        processor: "Intel Core i9-14900HX (24 Cores, 32 Threads, up to 5.8 GHz, MSI OverBoost Ultra 270W)",
        processorFamily: "Intel 14th Gen Raptor Lake Refresh",
        cpuArchitecture: "Intel 7 (8P + 16E)",
        powerClass: "Colossal Desktop Replacement (270W Total Combined Power)",
        gpu: "NVIDIA GeForce RTX 4090 16GB GDDR6 (175W TGP)",
        gpuModel: "GeForce RTX 4090",
        gpuVram: 16,
        gpuClass: "Ultra Flagship Gaming",
        tgp: 175,
        ram: "64GB DDR5-5600MHz (2x32GB)",
        ramType: "DDR5",
        ramUpgradeability: "Upgradeable to 192GB (4x DDR5 SO-DIMM slots)",
        storage: "4TB (2x2TB) NVMe PCIe Gen5 + Gen4 SSD",
        storageType: "NVMe Gen5 + Gen4",
        storageInterface: "PCIe 5.0 x4 + PCIe 4.0 x4 (3x M.2 Slots total)",
        displaySize: 18.0,
        resolution: "3840 x 2400 UHD+ 4K 16:10",
        refreshRate: 120,
        panelType: "Mini LED Display",
        colorCoverage: "100% DCI-P3 (1000 nits, VESA DisplayHDR 1000 certified)",
        battery: "99.9Whr 4-cell Li-Polymer (400W Power Adapter)",
        operatingSystem: "Windows 11 Pro",
        weight: "3.60 kg",
        ports: ["2x Thunderbolt 4 / USB Type-C (DP / USB-PD 3.1)", "3x USB 3.2 Gen 2 Type-A", "1x HDMI 2.1 (8K @ 60Hz / 4K @ 120Hz)", "1x SD Express Card Reader", "1x 2.5Gbps LAN"],
        wifi: "Intel Killer Wi-Fi 7 BE1750",
        bluetooth: "Bluetooth 5.4",
        webcam: "IR FHD type (30fps@1080p) with HDR & 3D Noise Reduction+ (3DNR+)",
        keyboard: "Cherry MX Ultra-Low Profile Mechanical Keyboard with per-key RGB & seamless RGB haptic touchpad",
        warranty: "2 Years Carry-in Warranty"
      },
      useCaseProfile: { gaming: 10.0, productivity: 10.0, editing: 10.0, rendering: 10.0, programming: 10.0, ai: 10.0, streaming: 10.0 }
    },

    // 29. Lenovo Legion 9i 16 (RTX 4090 16GB Liquid Cooled)
    {
      title: "Lenovo Legion 9i 16IRX9 (Intel Core i9-14900HX, RTX 4090 16GB, 64GB DDR5, 2TB SSD, 3.2K 165Hz Mini LED, Liquid Cooling) - Carbon Black",
      description: "World's first integrated liquid-cooled gaming laptop co-engineered with Cooler Master. Crafted with forged carbon A-cover, 64GB overclocked RAM, 175W RTX 4090, and 3.2K 165Hz Mini LED panel.",
      price: 519890,
      discountPrice: 449990,
      category: gamingCatId,
      brand: "Lenovo",
      stock: 6,
      featured: true,
      productType: "laptop",
      images: [
        { url: "/images/laptops/lenovo_legion_9i_1.jpg", publicId: "lenovo_legion_9i_1" },
        { url: "/images/laptops/lenovo_legion_9i_2.jpg", publicId: "lenovo_legion_9i_2" }
      ],
      rating: 5.0,
      numReviews: 24,
      specifications: {
        brand: "Lenovo",
        model: "Legion 9 16IRX9 (83G00018IN)",
        processor: "Intel Core i9-14900HX (24 Cores, 32 Threads, up to 5.8 GHz)",
        processorFamily: "Intel 14th Gen Raptor Lake Refresh",
        cpuArchitecture: "Intel 7 (8P + 16E)",
        powerClass: "Self-Contained Liquid Cooled (230W Total TDP)",
        gpu: "NVIDIA GeForce RTX 4090 16GB GDDR6 (175W TGP)",
        gpuModel: "GeForce RTX 4090",
        gpuVram: 16,
        gpuClass: "Ultra Flagship Gaming",
        tgp: 175,
        ram: "64GB DDR5-5600MHz (2x32GB Overclocked)",
        ramType: "DDR5",
        ramUpgradeability: "64GB Dual-Channel Overclocked",
        storage: "2TB (2x1TB) SSD M.2 2280 PCIe 4.0x4 NVMe in RAID 0",
        storageType: "NVMe RAID 0",
        storageInterface: "PCIe 4.0 x4 (Dual M.2 Slots)",
        displaySize: 16.0,
        resolution: "3200 x 2000 3.2K 16:10",
        refreshRate: 165,
        panelType: "Mini LED PureSight Gaming (3ms)",
        colorCoverage: "100% DCI-P3 & 100% Adobe RGB (1200 nits peak, VESA DisplayHDR 1000, G-Sync)",
        battery: "99.99Whr (330W GaN Slim Adapter + 140W USB-C PD Support)",
        operatingSystem: "Windows 11 Home",
        weight: "2.56 kg",
        ports: ["2x Thunderbolt 4 / USB-C 40Gbps", "1x USB-C 3.2 Gen 1 (PD 140W / DP 1.4)", "2x USB-A 3.2 Gen 1", "1x HDMI 2.1", "1x SD Card Reader 3.0", "1x 2.5G RJ-45"],
        wifi: "Killer Wi-Fi 7 BE1750",
        bluetooth: "Bluetooth 5.4",
        webcam: "1080p FHD with E-shutter",
        keyboard: "Per-Key RGB Legion TrueStrike with Ceramic Keycaps & Forged Carbon Lid",
        warranty: "3 Years Premier Onsite Support + 3 Years Legion Ultimate Support + 1 Year ADP"
      },
      useCaseProfile: { gaming: 10.0, productivity: 10.0, editing: 10.0, rendering: 10.0, programming: 10.0, ai: 10.0, streaming: 10.0 }
    },

    // 30. HP OMEN Transcend 16 (RTX 4080 12GB OLED)
    {
      title: "HP OMEN Transcend 16-u1005TX (Intel Core i9-14900HX, RTX 4080 12GB, 32GB DDR5, 1TB SSD, 240Hz OLED) - Shadow Black",
      description: "Ultra-thin 19.9mm magnesium-aluminum chassis packing 145W RTX 4080, 24-core i9-14900HX, 240Hz 0.2ms OLED display with 100% DCI-P3, and HyperX pudding keycaps.",
      price: 279990,
      discountPrice: 229990,
      category: gamingCatId,
      brand: "HP",
      stock: 12,
      featured: true,
      productType: "laptop",
      images: [
        { url: "/images/laptops/hp_omen_transcend_16_1.jpg", publicId: "hp_omen_transcend_16_1" },
        { url: "/images/laptops/hp_omen_transcend_16_2.jpg", publicId: "hp_omen_transcend_16_2" }
      ],
      rating: 4.9,
      numReviews: 31,
      specifications: {
        brand: "HP",
        model: "OMEN Transcend Laptop 16-u1005TX",
        processor: "Intel Core i9-14900HX (24 Cores, 32 Threads, up to 5.8 GHz)",
        processorFamily: "Intel 14th Gen Raptor Lake Refresh",
        cpuArchitecture: "Intel 7 (8P + 16E)",
        powerClass: "Ultra-Slim High-Performance (55W-145W)",
        gpu: "NVIDIA GeForce RTX 4080 12GB GDDR6 (145W TGP with Dynamic Boost)",
        gpuModel: "GeForce RTX 4080",
        gpuVram: 12,
        gpuClass: "Enthusiast Flagship Gaming",
        tgp: 145,
        ram: "32GB DDR5-5600MHz (2x16GB)",
        ramType: "DDR5",
        ramUpgradeability: "Upgradeable to 64GB (2x SO-DIMM)",
        storage: "1TB PCIe Gen4 NVMe TLC M.2 SSD",
        storageType: "NVMe SSD",
        storageInterface: "PCIe 4.0 x4",
        displaySize: 16.0,
        resolution: "2560 x 1600 WQXGA OLED 16:10",
        refreshRate: 240,
        panelType: "OLED Display (0.2ms)",
        colorCoverage: "100% DCI-P3 (500 nits HDR, VESA True Black 400, Eyesafe certified)",
        battery: "97Whr 6-cell Li-ion polymer (Fast charge 50% in 30min)",
        operatingSystem: "Windows 11 Home",
        weight: "2.14 kg",
        ports: ["2x Thunderbolt 4 with USB Type-C 40Gbps", "2x USB Type-A 10Gbps (HP Sleep and Charge)", "1x HDMI 2.1", "1x RJ-45 Gigabit Ethernet", "1x Headphone/mic combo"],
        wifi: "Intel Wi-Fi 7 BE200 (2x2)",
        bluetooth: "Bluetooth 5.4",
        webcam: "HP True Vision 1080p FHD IR camera with temporal noise reduction",
        keyboard: "Per-Key RGB Shadow Black Backlit Keyboard with HyperX Pudding Keycaps",
        warranty: "1 Year Onsite Warranty"
      },
      useCaseProfile: { gaming: 9.7, productivity: 9.8, editing: 9.8, rendering: 9.6, programming: 9.8, ai: 9.4, streaming: 9.6 }
    },
  ];
};
